server:
#  port: 9080
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: java-practice
  devtools:
    remote:
      proxy:
        host: localhost
        port: 8080
      restart:
        enabled: true
    livereload:         # Hot Reload
      enabled: true
    restart:            # Hot Reload
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    rest:
      base-path: /api
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  # H2 Database
  datasource:
    url: jdbc:h2:mem:sample_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      encoding: utf-8
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

# log
#logging:
#  level:
#    org:
#      springframework:
#        web: debug
#        security: info
#  pattern:
#    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
#    level: '%5p USER_ID:%X{USER_ID} SESSION_ID:%X{SESSION_ID} TRACE_ID:%X{traceId}'